- name: Add apt repository for stable version
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  state: present

- name: Install docker and its dependecies
  yum: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - containerd.io
  notify:
    - docker status

# $ sudo usermod -a -G docker $USER
- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker