- name: Install packages that allow apt to be used over HTTPS
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  register: stuff
- debug: msg="{{ stuff.stdout_lines }}"